### ISSUE TITLE
support for injecting packages

### ISSUE THREAD

**Issue by elevaitleo** [mariusvniekerk/condax#12]
Thanks for this package, it solves exactly my use-case.

However, to be complete, I would need to be able to inject some packages into some environment. This is needed for developing own packages that depend on conda packages.

Do you have any idea if this is supported, and if not how hard it would be to support it?

**Comment by mariusvniekerk** [comment]
What do you mean by injecting packages?
condax installs a fully working conda environment and just harvests entrypoints from the "leaf" level package

**Comment by mforbes** [comment]
@mariusvniekerk: Not sure if this is @elevaitleo's use-case, but as an example: I would like to use `condax` to install Mercurial with several extensions like `hg-git` and `evolve`.  I currently do this with an environment file like the following, where I need some extra packages to enable these extensions.  How would I do this with `condax`?

```yaml
name: hg
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3
  - mercurial >= 5.6
  - pygit2
  - hg-git
  - hg-evolve
  
  - pip
  - pip:
    - python-hglib
    - mmf-setup
```
